// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/mhaqiw/haqi-coba-golang/domain"
	mock "github.com/stretchr/testify/mock"
)

// ProductStockUsecase is an autogenerated mock type for the ProductStockUsecase type
type ProductStockUsecase struct {
	mock.Mock
}

// Update provides a mock function with given fields: ctx, request
func (_m *ProductStockUsecase) Update(ctx context.Context, request domain.ProductStockUpdateRequest) (int, error) {
	ret := _m.Called(ctx, request)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProductStockUpdateRequest) int); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.ProductStockUpdateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
