// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WarehouseRepository is an autogenerated mock type for the WarehouseRepository type
type WarehouseRepository struct {
	mock.Mock
}

// CheckWarehouseByID provides a mock function with given fields: id
func (_m *WarehouseRepository) CheckWarehouseByID(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
